title: "{{ replace .Name \"-\" \" \" | title }}"
size: "8.5 x 11\""
description: >-
  Detailed description of the product goes here. This should be a few sentences that explain what the product is and its main benefits.
features:
  - "Size 8.5 x 11\""
  - "Waterproof material"
  - "Highly visible"
  - "Fade resistant"
  - "Die cut on back"
  - "Full color printing available"
  - "No set up charge"
  - "1-part, self-adhesive, 4 sides"
price: 0.00
price_note: "per item (min quantity)"
# best_price_note: "Best Price for AK Dealer Services"
purchase_links:
  - name: "Buy on AK Dealer Services"
    url: "https://akdealerservices.com/product/1000000-product-name"
  - name: "Buy on Amazon"
    url: "#"
  - name: "Wholesale Inquiry"
    url: "#wholesale"
images:
  - src: "images/CATEGORY/product-image-1.jpg"
  - src: "images/CATEGORY/product-image-2.jpg"
  - src: "images/CATEGORY/product-image-3.jpg"
