[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.140.2"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "https://autowindowstickers.com/"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

# Try existing files first
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  
# Then try dynamic routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Security headers
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; img-src 'self' data: https:; connect-src 'self' https:;"
    
# Cache control for static assets
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,ico,svg,woff,woff2,ttf,eot,otf,css,js}"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
