# Portable config for tools/page-generator

execution:
  seed: 42                      # Random seed for reproducible generation
  limit: 2                      # Max number of pages to generate (0 = unlimited)
  dry_run: false                # If true, preview without creating files
  base_path: "../.."            # Root of the Hugo site
  output_dir: "content"         # Output directory relative to base_path

content:
  savings_count: 1              # Number of savings items per page
  benefits_count: 6             # Number of benefit items per page
  faq_count: 10                 # Number of FAQ items per page
  testimonials_count: 3         # Number of testimonial items per page
  default_saving_number: "3500" # Default savings amount for placeholders

seo:
  seo_keywords_file: "data/content-generator/keywords-seotitle.yaml"      # Keywords for seoTitle only
  content_keywords_file: "data/content-generator/keywords.yaml"           # Keywords for [[keyword]] placeholders
  title_template: "{product_title} — {keyword} {state}"                   # Template for page titles

pages:
  layout: "product"                                                        # Hugo layout to use
  filename_pattern: "states/{state_slug}/{product_key}/index.md"          # Output file path pattern for state pages
  base_product_pattern: "{category}/{product_key}/index.md"               # Output file path pattern for base product pages

data_sources:
  products_dir: "data/products"                                            # Directory with product YAML files
  states_file: "data/content-generator/states.yaml"                       # File with US states data
